### ISSUE TITLE
drupal:9.2-fpm-alpine outdated

### ISSUE THREAD

**Issue by jlcharette** [drupalwxt/docker-scaffold#16]
docker-scaffold currently use `drupal:9.2-fpm-alpine` which installs an outdated version of php < 8.1 resulting in fatal error while trying to run `make drupal_install`.

![image](https://user-images.githubusercontent.com/44408591/178058596-8b807347-7f89-4130-955c-e8a79a487804.png)

Current env:
Windows with WSL2 (Ubuntu 20.04.4 LTS)
Docker 20.10.12
Composer 2.3.8
Git 2.25.1

**Comment by sylus** [comment]
HI there we currently support php 8.0 and are working on php 8.1 support but a dep for azure mysqlnd_azure needs updates for it. 

The problem you have however is different and you ran composer install on your machine which has php 8.1 and our containers for the moment are on php 8.0

Just run your composer install with 

```
    composer install --prefer-dist \
                     --ignore-platform-reqs 
```

And it should be fine! Thx!
