### ISSUE TITLE
Latest version of docker compose fails to start containers

### ISSUE THREAD

**Issue by smulvih2** [drupalwxt/docker-scaffold#38]
I'm using the latest version of docker compose, and running a `docker compose up -d` now results in:

```
service "web" can't be used with `extends` as it declare `depends_on`
make: *** [docker/Makefile:63: docker_start] Error 15
```

Looks like docker compose 2.24.6 introduces this breaking change, see related issue - [https://github.com/docker/compose/issues/11544](https://github.com/docker/compose/issues/11544)

**Comment by sylus** [comment]
Seems its fixed in the subsequent release?

**Comment by smulvih2** [comment]
Will test the new release if available and report back

**Comment by smulvih2** [comment]
Ok ya so updating from docker 25.0.4 (docker compose 2.24.7) to docker 26.0.0 (docker compose 2.25.0) fixed the issue for me. Wanted to log this issue when I ran into it, caught me off guard as I didn't update docker or related packages when this started happening. Closing ticket now.
